# Docker Image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'trimesh'
  dockerId: 'mikedh'

env:
  dockerPass: $(DOCKER_PASS)

steps:
- script: |
    docker login -u $(dockerId) -p $env:dockerPass
    docker build -t $(dockerId)/$(imageName) .
    docker push $(dockerId)/$(imageName):latest
  displayName: 'docker build'
