# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    filters:
      branches:
        only: master
    docker:
      - image: continuumio/anaconda3
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apt-get update; apt-get install -qq -y meshlab xvfb blender openscad
            pip install pytest
            pip install .
            python -c "import trimesh"
            pytest -p no:warnings tests/test_inertia.py
            conda install --quiet -y -c conda-forge rtree shapely pyembree
            pip install .[easy]
      - run:
          name: run tests
          command: pytest -W default tests

  dockerImage:
    working_directory: ~/repo
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build . -t "mikedh/trimesh"
      - deploy:
          name: Push To DockerHub
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASS}
            docker push "mikedh/trimesh"
